/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DSlugIndexRouteImport } from './routes/d.$slug.index'
import { Route as DSlugListaIndexRouteImport } from './routes/d.$slug.$lista.index'
import { Route as DSlugListaExercicioRouteImport } from './routes/d.$slug.$lista.$exercicio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugIndexRoute = DSlugIndexRouteImport.update({
  id: '/d/$slug/',
  path: '/d/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugListaIndexRoute = DSlugListaIndexRouteImport.update({
  id: '/d/$slug/$lista/',
  path: '/d/$slug/$lista/',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugListaExercicioRoute = DSlugListaExercicioRouteImport.update({
  id: '/d/$slug/$lista/$exercicio',
  path: '/d/$slug/$lista/$exercicio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/d/$slug/$lista/$exercicio': typeof DSlugListaExercicioRoute
  '/d/$slug/$lista/': typeof DSlugListaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/d/$slug': typeof DSlugIndexRoute
  '/d/$slug/$lista/$exercicio': typeof DSlugListaExercicioRoute
  '/d/$slug/$lista': typeof DSlugListaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/d/$slug/$lista/$exercicio': typeof DSlugListaExercicioRoute
  '/d/$slug/$lista/': typeof DSlugListaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/d/$slug/'
    | '/d/$slug/$lista/$exercicio'
    | '/d/$slug/$lista/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/d/$slug' | '/d/$slug/$lista/$exercicio' | '/d/$slug/$lista'
  id:
    | '__root__'
    | '/'
    | '/d/$slug/'
    | '/d/$slug/$lista/$exercicio'
    | '/d/$slug/$lista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DSlugIndexRoute: typeof DSlugIndexRoute
  DSlugListaExercicioRoute: typeof DSlugListaExercicioRoute
  DSlugListaIndexRoute: typeof DSlugListaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug/': {
      id: '/d/$slug/'
      path: '/d/$slug'
      fullPath: '/d/$slug/'
      preLoaderRoute: typeof DSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug/$lista/': {
      id: '/d/$slug/$lista/'
      path: '/d/$slug/$lista'
      fullPath: '/d/$slug/$lista/'
      preLoaderRoute: typeof DSlugListaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug/$lista/$exercicio': {
      id: '/d/$slug/$lista/$exercicio'
      path: '/d/$slug/$lista/$exercicio'
      fullPath: '/d/$slug/$lista/$exercicio'
      preLoaderRoute: typeof DSlugListaExercicioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DSlugIndexRoute: DSlugIndexRoute,
  DSlugListaExercicioRoute: DSlugListaExercicioRoute,
  DSlugListaIndexRoute: DSlugListaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
